name: build waf dockers
  
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'A token passed from the caller workflow'
        required: false
      DOCKERHUB_TOKEN:
        description: 'A token passed from the caller workflow'
        required: false

  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push TADK
        uses: docker/build-push-action@v4
        with:
          context: TADK
          platforms: linux/amd64
          push: true
          tags: kingfs/TADK:v23.03.0